spring:
  application:
    name: springboot-learing
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:springboot-learning.db
    username: user
    password: 12345678

  # 数据迁移配置
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

# 配置mybatis规则
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
