spring:
  application:
    name: springboot-learing
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app?useUnicode=true&characterEncoding=utf-8
    username: user
    password: 12345678

  # 数据迁移配置
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

# 配置mybatis规则
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true