version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # 开启 Redis 的 AOF 持久化模式（可选）
  # 配置一个 nginx 自定义配置
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
  # 配置一个 mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql

  swagger:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "8088:8080"

volumes:
  redis_data:
  mysql_data:
