//文本字符串处理的drl文件
package rules.word;
import cn.danao.bean.WordObj;
import cn.danao.bean.RuleType
import java.util.List
import java.util.ArrayList
import java.util.HashMap
import java.util.Map;

function void print(String args){
     System.out.println("修改规则处的打印" + args);
}

rule "one"

when
    $word:WordObj($word.getRuleType().equals(RuleType.ONE))
then
    print($word.toString());
    $word.setKey("测试修改one");
//    update($word)
end

rule "two"

when
    $word:WordObj($word.getRuleType().equals(RuleType.TWO))
then
    $word.setKey("修改规则two");
    List<String> list = new ArrayList<>();
    list.add("aa");
    list.add("aa");
    list.add("aa");
    list.add("aa");
    $word.setList(list);
    print($word.toString());
end

rule "three"

when
    $word:WordObj($word.getRuleType().equals(RuleType.THREE))
then
    $word.setKey("修改规则three");
    Map<String,Object> map = new HashMap<>();
    map.put("a","b");
    map.put("aa","b");
    $word.setMap(map);
    print($word.toString());
end

rule "fore"

when
    $word:WordObj($word.getRuleType().equals(RuleType.FORE))
then
    $word.setKey("修改规则fore");
    print($word.toString());
end

rule "five"

when
    $word:WordObj($word.getRuleType().equals(RuleType.FIVE))
then
    $word.setKey("修改规则five");
    print($word.toString());
end

rule "six"
