package rules

import cn.danao.bean.User;

/*
这里面可以分成几个部分：

3.1 package部分

这个是用来管理包的，跟java的package概念类似，多个rule文件时，可以按包来管理rule代码。

3.2 import

drl 规则文件中，可以直接使用java定义好的类，只需要import进来就好。

3.3 global

相当于全局变量声明，多个规则文件中可共享该变量（后面会演示这一用法），
要注意的是：共享全局变量建议不要用Integer这种"简单"类型，这样无法在规则文件中修改变量的"值"，
建议用复杂类型（比如上面的AtomicInteger）

3.4 function

即：函数，可以定义一些共用函数，在本drl文件被其它规则共用。

3.5 rule ... when ... then ... end

这个就是真正的规则了，rule后面的"say-hi"为规则名称，
when后面的相当于判断条件（注：声明条件的同时，还能声明所谓fact"变量"-[不太准确，暂且这样叫吧]，
message:Message(...)这里就相当于把后面一串东西，保存在message这个fact"变量中）
*/

//规则
rule "HelloWorld"
    //简单规则测试
    when
        u:User(age>18)
    then
        System.out.println( u.getName() + "成年了" );
end
